const mongoose = require('mongoose');

const sheetSchema = new mongoose.Schema ({
    informacoes: {
        nome: {type: String, required: true},
        profissao: String,
        naturalidade: String,
        residencia: String,
        pronome: String,
        idade: Number
    },
    caracteristicas: {
        status: {
            FOR: Number,
            CON: Number,
            DES: Number,
            INT: Number,
            TAM: Number,
            POD: Number,
            APA: Number,
            EDU: Number,
            SORTE: {
                inicial: Number,
                atual: Number
            }
        },
        hp: Number,
        mp: Number,
        sanidade: {
            inicial: Number,
            atual: Number
        },
        estados: {
            insanidadeTemp: {type: Boolean, default: false},
            insanidadeIndef: {type: Boolean, default: false},
            lesaoGrave: { type: Boolean, default: false },
            inconsciente: { type: Boolean, default: false },
            morrendo: { type: Boolean, default: false }
        }
    },
    habilidades: {
        antropologia: {valor: Number, melhorar: {type: Boolean, default: false}},
        arco: {valor: Number, melhorar: {type: Boolean, default: false}},
        armasPesadas: {valor: Number, melhorar: {type: Boolean, default: false}},
        arqueologia: {valor: Number, melhorar: {type: Boolean, default: false}},
        artilharia: {valor: Number, melhorar: {type: Boolean, default: false}},
        astronomia: {valor: Number, melhorar: {type: Boolean, default: false}},
        atuacao: {valor: Number, melhorar: {type: Boolean, default: false}},
        avaliacao: {valor: Number, melhorar: {type: Boolean, default: false}},
        belasArtes: {valor: Number, melhorar: {type: Boolean, default: false}},
        biologia: {valor: Number, melhorar: {type: Boolean, default: false}},
        botanica: {valor: Number, melhorar: {type: Boolean, default: false}},
        briga: {valor: Number, melhorar: {type: Boolean, default: false}},
        charme: {valor: Number, melhorar: {type: Boolean, default: false}},
        chaveiro: {valor: Number, melhorar: {type: Boolean, default: false}},
        chicote: {valor: Number, melhorar: {type: Boolean, default: false}},
        contabilidade: {valor: Number, melhorar: {type: Boolean, default: false}},
        credito: {valor: Number, melhorar: {type: Boolean, default: false}},
        criptografia: {valor: Number, melhorar: {type: Boolean, default: false}},
        cthulhuMythos: {valor: Number, melhorar: {type: Boolean, default: false}},
        demolicao: {valor: Number, melhorar: {type: Boolean, default: false}},
        dirigir: {valor: Number, melhorar: {type: Boolean, default: false}},
        disfarce: {valor: Number, melhorar: {type: Boolean, default: false}},
        encontrar: {valor: Number, melhorar: {type: Boolean, default: false}},
        escalar: {valor: Number, melhorar: {type: Boolean, default: false}},
        escutar: {valor: Number, melhorar: {type: Boolean, default: false}},
        espada: {valor: Number, melhorar: {type: Boolean, default: false}},
        espingarda: {valor: Number, melhorar: {type: Boolean, default: false}},
        esquiva: {valor: Number, melhorar: {type: Boolean, default: false}},
        falsificacao: {valor: Number, melhorar: {type: Boolean, default: false}},
        farmacia: {valor: Number, melhorar: {type: Boolean, default: false}},
        fotografia: {valor: Number, melhorar: {type: Boolean, default: false}},
        furtividade: {valor: Number, melhorar: {type: Boolean, default: false}},
        garrote: {valor: Number, melhorar: {type: Boolean, default: false}},
        geologia: {valor: Number, melhorar: {type: Boolean, default: false}},
        hipnose: {valor: Number, melhorar: {type: Boolean, default: false}},
        historia: {valor: Number, melhorar: {type: Boolean, default: false}},
        idiomaNativo: {valor: Number, melhorar: {type: Boolean, default: false}},
        idiomaOutro: {valor: Number, melhorar: {type: Boolean, default: false}},
        intimidacao: {valor: Number, melhorar: {type: Boolean, default: false}},
        labia: {valor: Number, melhorar: {type: Boolean, default: false}},
        lanca: {valor: Number, melhorar: {type: Boolean, default: false}},
        lancaChamas: {valor: Number, melhorar: {type: Boolean, default: false}},
        lancar: {valor: Number, melhorar: {type: Boolean, default: false}},
        lei: {valor: Number, melhorar: {type: Boolean, default: false}},
        leituraLabial: {valor: Number, melhorar: {type: Boolean, default: false}},
        machado: {valor: Number, melhorar: {type: Boolean, default: false}},
        mangual: {valor: Number, melhorar: {type: Boolean, default: false}},
        maquinasPesadas: {valor: Number, melhorar: {type: Boolean, default: false}},
        manejoAnimais: {valor: Number, melhorar: {type: Boolean, default: false}},
        matematica: {valor: Number, melhorar: {type: Boolean, default: false}},
        medicina: {valor: Number, melhorar: {type: Boolean, default: false}},
        mergulho: {valor: Number, melhorar: {type: Boolean, default: false}},
        meteorologia: {valor: Number, melhorar: {type: Boolean, default: false}},
        metralhadora: {valor: Number, melhorar: {type: Boolean, default: false}},
        motosserra: {valor: Number, melhorar: {type: Boolean, default: false}},
        mundoNatural: {valor: Number, melhorar: {type: Boolean, default: false}},
        nadar: {valor: Number, melhorar: {type: Boolean, default: false}},
        navegacao: {valor: Number, melhorar: {type: Boolean, default: false}},
        ocultismo: {valor: Number, melhorar: {type: Boolean, default: false}},
        pericia: {valor: Number, melhorar: {type: Boolean, default: false}},
        persuasao: {valor: Number, melhorar: {type: Boolean, default: false}},
        pilotar: {valor: Number, melhorar: {type: Boolean, default: false}},
        pistola: {valor: Number, melhorar: {type: Boolean, default: false}},
        presdigitacao: {valor: Number, melhorar: {type: Boolean, default: false}},
        primeirosSocorros: {valor: Number, melhorar: {type: Boolean, default: false}},
        psicanalise: {valor: Number, melhorar: {type: Boolean, default: false}},
        psicologia: {valor: Number, melhorar: {type: Boolean, default: false}},
        quimica: {valor: Number, melhorar: {type: Boolean, default: false}},
        rastrear: {valor: Number, melhorar: {type: Boolean, default: false}},
        reparoEletrico: {valor: Number, melhorar: {type: Boolean, default: false}},
        reparoMecanico: {valor: Number, melhorar: {type: Boolean, default: false}},
        rifle: {valor: Number, melhorar: {type: Boolean, default: false}},
        saltar: {valor: Number, melhorar: {type: Boolean, default: false}},
        sobrevivencia: {valor: Number, melhorar: {type: Boolean, default: false}},
        submetralhadora: {valor: Number, melhorar: {type: Boolean, default: false}},
        biblioteca: {valor: Number, melhorar: {type: Boolean, default: false}},
        computadores: {valor: Number, melhorar: {type: Boolean, default: false}},
        zoologia: {valor: Number, melhorar: {type: Boolean, default: false}}
    },
    combate: {
        arma1: {
            nome: String,
            valor: Number,
            dano: String,
            ataques: Number,
            alcance: Number,
            pente: Number,
            falha: Number
        },
        arma2: {
            nome: String,
            valor: Number,
            dano: String,
            ataques: Number,
            alcance: Number,
            pente: Number,
            falha: Number
        },
        arma3: {
            nome: String,
            valor: Number,
            dano: String,
            ataques: Number,
            alcance: Number,
            pente: Number,
            falha: Number
        }
    },
    historia: {
        backstory: String,
        descricao: String,
        tracos: String,
        crencas: String,
        ferimentos: String,
        pessoas: String,
        fobias: String,
        locais: String,
        feiticos: String,
        pertences: String,
        encontros: String,
        inventario: String
    },
    economias: {
        nivelGasto: Number,
        dinheiro: Number,
        ativos: String
    },
    notas: String
})

const Sheet = mongoose.model('Sheet', sheetSchema);